---
abstract: 'An AnyEvent-based TCP server providing a RESTful interface.'
author:
  - 'Raphael Seebacher <raphael@seebachers.ch>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-REST-Server
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 7.04
  Object::Event: 1.23
version: 0.05
